#!/usr/bin/env bash
set -e
psql -v ON_ERROR_STOP=1 -U "$PGUSER" -d "$PGDATABASE" <<-EOSQL
  CREATE USER $DB_USER WITH LOGIN PASSWORD '$DB_PASS';
  CREATE DATABASE $DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
  \connect $DB_NAME $DB_USER
  BEGIN;

CREATE TABLE patients (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	first_name VARCHAR NOT NULL,
	middle_name VARCHAR,
	last_name VARCHAR NOT NULL,
	birth_date DATE NOT NULL,
	to_committee BOOLEAN NOT NULL,
	to_internat BOOLEAN NOT NULL,
	CONSTRAINT patient_uc UNIQUE (first_name, middle_name, last_name, birth_date, to_committee, to_internat)
);
CREATE TABLE doctors (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	name VARCHAR NOT NULL UNIQUE,
	expires_in_months INTEGER NOT NULL
);
CREATE TABLE diagnostics (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	name VARCHAR NOT NULL UNIQUE,
	expires_in_months INTEGER NOT NULL
);
CREATE TABLE patients_doctors (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	patient_id INTEGER,
	doctor_id INTEGER,
	last_at DATE,
	FOREIGN KEY(patient_id) REFERENCES patients (id),
	FOREIGN KEY(doctor_id) REFERENCES doctors (id)
);
CREATE TABLE patients_diagnostics (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	patient_id INTEGER,
	diagnostic_id INTEGER,
	last_at DATE,
	FOREIGN KEY(patient_id) REFERENCES patients (id),
	FOREIGN KEY(diagnostic_id) REFERENCES diagnostics (id)
);
INSERT INTO diagnostics (name, expires_in_months)
VALUES
('Серология', 6),
('BD', 6),
('BL', 6),
('ОАК', 3),
('ОАМ', 3),
('Биохимия', 3),
('Титры', 9999),
('COVID - кровь', 1),
('COVID - мазок', 999),
('Глик.Гемоглобин', 999),
('Онкомаркеры', 999),
('Мокрота на АБ', 999),
('Моча на АБ', 999),
('Я/Г., Стронг', 999),
('Энтеробиоз', 999),
('УЗИ', 999),
('ЭКГ', 3),
('Флюорография', 6),
('Рентген', 999);
INSERT INTO doctors (name, expires_in_months)
VALUES
('Терапевт', 6),
('Невролог', 6),
('Окулист', 999),
('Дерматолог', 999),
('ЛОГ', 999),
('Хирург', 999),
('ФТО', 999),
('Онколог', 999),
('Фтизиатр', 999),
('Стоматолог', 999),
('Инфекционист', 999);
COMMIT;
EOSQL