"""medical crud updated v2

Revision ID: 74fcb8d6afe9
Revises: eb347b9c8bb8
Create Date: 2021-12-13 18:42:56.270046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74fcb8d6afe9'
down_revision = 'eb347b9c8bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'medical_insurance',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'medical_insurance',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
